//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTELPRO.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATIS
    {
        public int satısId { get; set; }
        public Nullable<int> danısan { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<int> oda { get; set; }
        public Nullable<int> gun { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual TBLDANISMAN TBLDANISMAN { get; set; }
        public virtual TBLMUSTERI TBLMUSTERI { get; set; }
        public virtual TBLODA TBLODA { get; set; }
    }
}
